/**
 * Cohort Analysis Routes
 * Handles cohort creation, metrics, and analysis
 */

import { Router, Request, Response } from 'express';
import { prisma } from '../lib/prisma';
import { authenticate } from '../middleware/auth';
import { userRateLimiter } from '../middleware/rateLimit';
import { asyncHandler } from '../middleware/asyncHandler';
import { BadRequestError, NotFoundError } from '../lib/errors';
import {
  findUsersMatchingCriteria,
  getCohortRetentionData,
  generateCohorts,
  calculateCohortMetrics,
  calculateAllCohortMetrics,
  CohortDefinition,
} from '../lib/analytics/cohortAnalysis';
import { generateAutomaticCohorts } from '../lib/analytics/cohortGeneration';
import {
  linearRegressionPrediction,
  movingAveragePrediction,
  mlPrediction,
  combinedPrediction,
} from '../lib/analytics/predictiveAnalytics';

const router = Router();

/**
 * GET /api/cohorts
 * Get all cohorts
 */
router.get(
  '/',
  authenticate,
  userRateLimiter,
  asyncHandler(async (req: Request, res: Response) => {
    // TODO: Check if user is admin

    // Filter parameters
    const { platform, country, planType, signupSource, region } = req.query;

    const where: any = {};
    if (platform) where.platform = platform;
    if (country) where.country = country;
    if (planType) where.planType = planType;
    if (signupSource) where.signupSource = signupSource;

    const cohorts = await prisma.userCohort.findMany({
      where,
      orderBy: { createdAt: 'desc' },
      include: {
        _count: {
          select: { metrics: true },
        },
      },
    });

    // Filter by region if provided (region maps to countries)
    let filteredCohorts = cohorts;
    if (region) {
      const regionCountries: Record<string, string[]> = {
        US: ['US'],
        EU: ['DE', 'FR', 'IT', 'ES', 'NL', 'BE', 'AT', 'SE', 'DK', 'FI', 'PL', 'IE', 'PT', 'GR'],
        APAC: ['IN', 'JP', 'KR', 'CN', 'AU', 'SG', 'MY', 'TH', 'ID', 'PH', 'VN'],
      };
      const countries = regionCountries[region as string] || [];
      filteredCohorts = cohorts.filter(c => c.country && countries.includes(c.country));
    }

    res.json({
      success: true,
      data: filteredCohorts.map(c => ({
        id: c.id,
        name: c.name,
        definition: c.definition,
        userCount: c.userIds.length,
        metricsCount: c._count.metrics,
        platform: c.platform,
        country: c.country,
        planType: c.planType,
        signupSource: c.signupSource,
        autoGenerated: c.autoGenerated,
        createdAt: c.createdAt,
        updatedAt: c.updatedAt,
      })),
    });
  })
);

/**
 * GET /api/cohorts/:id
 * Get cohort details with retention data
 */
router.get(
  '/:id',
  authenticate,
  userRateLimiter,
  asyncHandler(async (req: Request, res: Response) => {
    const { id } = req.params;

    // TODO: Check if user is admin

    const cohortData = await getCohortRetentionData(id);

    res.json({
      success: true,
      data: cohortData,
    });
  })
);

/**
 * POST /api/cohorts
 * Create a new cohort
 */
router.post(
  '/',
  authenticate,
  userRateLimiter,
  asyncHandler(async (req: Request, res: Response) => {
    const { name, definition, platform, country, planType, signupSource } = req.body;

    if (!name || !definition) {
      throw new BadRequestError('Name and definition are required');
    }

    // TODO: Check if user is admin

    // Find users matching criteria
    const userIds = await findUsersMatchingCriteria(definition as CohortDefinition);

    const cohort = await prisma.userCohort.create({
      data: {
        name,
        definition: definition as CohortDefinition,
        userIds,
        platform: platform || null,
        country: country || null,
        planType: planType || null,
        signupSource: signupSource || null,
      },
    });

    res.json({
      success: true,
      data: {
        id: cohort.id,
        name: cohort.name,
        userCount: cohort.userIds.length,
      },
    });
  })
);

/**
 * PUT /api/cohorts/:id
 * Update cohort
 */
router.put(
  '/:id',
  authenticate,
  userRateLimiter,
  asyncHandler(async (req: Request, res: Response) => {
    const { id } = req.params;
    const { name, definition } = req.body;

    // TODO: Check if user is admin

    const cohort = await prisma.userCohort.findUnique({
      where: { id },
    });

    if (!cohort) {
      throw new NotFoundError('Cohort not found');
    }

    let userIds = cohort.userIds;
    if (definition) {
      userIds = await findUsersMatchingCriteria(definition as CohortDefinition);
    }

    const updated = await prisma.userCohort.update({
      where: { id },
      data: {
        ...(name && { name }),
        ...(definition && { definition: definition as CohortDefinition }),
        userIds,
      },
    });

    res.json({
      success: true,
      data: updated,
    });
  })
);

/**
 * DELETE /api/cohorts/:id
 * Delete cohort
 */
router.delete(
  '/:id',
  authenticate,
  userRateLimiter,
  asyncHandler(async (req: Request, res: Response) => {
    const { id } = req.params;

    // TODO: Check if user is admin

    await prisma.userCohort.delete({
      where: { id },
    });

    res.json({
      success: true,
      message: 'Cohort deleted',
    });
  })
);

/**
 * POST /api/cohorts/generate
 * Generate automatic cohorts
 */
router.post(
  '/generate',
  authenticate,
  userRateLimiter,
  asyncHandler(async (req: Request, res: Response) => {
    // TODO: Check if user is admin

    await generateAutomaticCohorts();

    res.json({
      success: true,
      message: 'Cohorts generated successfully',
    });
  })
);

/**
 * GET /api/cohorts/:id/predictions
 * Get predictive analytics for a cohort
 */
router.get(
  '/:id/predictions',
  authenticate,
  userRateLimiter,
  asyncHandler(async (req: Request, res: Response) => {
    const { id } = req.params;
    const { method = 'combined', weeksAhead = 4 } = req.query;

    const cohortData = await getCohortRetentionData(id);
    const retentionData = cohortData.retentionByWeek.filter(r => r > 0);

    if (retentionData.length < 2) {
      return res.json({
        success: true,
        data: [],
        message: 'Not enough historical data for predictions',
      });
    }

    let predictions;
    switch (method) {
      case 'linear':
        predictions = linearRegressionPrediction(retentionData, Number(weeksAhead));
        break;
      case 'moving_average':
        predictions = movingAveragePrediction(retentionData, 3, Number(weeksAhead));
        break;
      case 'ml':
        predictions = mlPrediction(retentionData, 0.3, Number(weeksAhead));
        break;
      default:
        predictions = combinedPrediction(retentionData, Number(weeksAhead));
    }

    res.json({
      success: true,
      data: {
        historical: retentionData,
        predictions,
        method: method as string,
      },
    });
  })
);

/**
 * GET /api/cohorts/compare
 * Compare two cohorts side-by-side
 */
router.get(
  '/compare',
  authenticate,
  userRateLimiter,
  asyncHandler(async (req: Request, res: Response) => {
    const { cohort1Id, cohort2Id } = req.query;

    if (!cohort1Id || !cohort2Id) {
      throw new BadRequestError('cohort1Id and cohort2Id are required');
    }

    const [cohort1, cohort2] = await Promise.all([
      getCohortRetentionData(cohort1Id as string),
      getCohortRetentionData(cohort2Id as string),
    ]);

    res.json({
      success: true,
      data: {
        cohort1,
        cohort2,
      },
    });
  })
);

/**
 * GET /api/cohorts/:id/export
 * Export cohort data as CSV/Excel
 */
router.get(
  '/:id/export',
  authenticate,
  userRateLimiter,
  asyncHandler(async (req: Request, res: Response) => {
    const { id } = req.params;
    const { format = 'csv' } = req.query;

    const cohortData = await getCohortRetentionData(id);
    const cohort = await prisma.userCohort.findUnique({
      where: { id },
    });

    if (!cohort) {
      throw new NotFoundError('Cohort not found');
    }

    if (format === 'csv') {
      // Generate CSV
      const csvRows: string[] = [];
      
      // Header
      csvRows.push('Week,Active Users,New Users,Churned Users,Avg Watch Time (min),Avg Revenue,Retention %');
      
      // Data rows
      cohortData.metrics.forEach((metric, index) => {
        csvRows.push(
          `${index + 1},${metric.activeUsers},${metric.newUsers},${metric.churnedUsers},${Math.round(metric.avgWatchTime / 60)},${metric.avgRevenue.toFixed(2)},${(metric.retention * 100).toFixed(2)}`
        );
      });

      const csv = csvRows.join('\n');
      
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename="cohort-${cohort.name}-${Date.now()}.csv"`);
      res.send(csv);
    } else {
      // For Excel, we'd use a library like exceljs
      // For now, return JSON
      res.json({
        success: true,
        data: {
          cohort: {
            name: cohort.name,
            userCount: cohort.userIds.length,
            platform: cohort.platform,
            country: cohort.country,
            planType: cohort.planType,
            signupSource: cohort.signupSource,
          },
          metrics: cohortData.metrics,
        },
        message: 'Excel export not yet implemented. Use CSV format.',
      });
    }
  })
);

/**
 * POST /api/cohorts/:id/calculate-metrics
 * Calculate metrics for a specific cohort
 */
router.post(
  '/:id/calculate-metrics',
  authenticate,
  userRateLimiter,
  asyncHandler(async (req: Request, res: Response) => {
    const { id } = req.params;
    const { date } = req.body;

    // TODO: Check if user is admin

    const cohort = await prisma.userCohort.findUnique({
      where: { id },
    });

    if (!cohort) {
      throw new NotFoundError('Cohort not found');
    }

    const targetDate = date ? new Date(date) : new Date();
    await calculateCohortMetrics(id, targetDate);

    res.json({
      success: true,
      message: 'Metrics calculated successfully',
    });
  })
);

/**
 * POST /api/cohorts/calculate-all-metrics
 * Calculate metrics for all cohorts
 */
router.post(
  '/calculate-all-metrics',
  authenticate,
  userRateLimiter,
  asyncHandler(async (req: Request, res: Response) => {
    // TODO: Check if user is admin

    await calculateAllCohortMetrics();

    res.json({
      success: true,
      message: 'All cohort metrics calculated successfully',
    });
  })
);

export default router;

