/**
 * Automatic Cohort Generation
 * Generates cohorts based on common criteria
 */

import { prisma } from '../prisma';
import { findUsersMatchingCriteria, CohortDefinition } from './cohortAnalysis';

export interface AutoCohortConfig {
  name: string;
  definition: CohortDefinition;
  platform?: string;
  country?: string;
  planType?: string;
  signupSource?: string;
}

/**
 * Generate automatic cohorts
 */
export async function generateAutomaticCohorts(): Promise<void> {
  console.log('Generating automatic cohorts...');

  const cohortConfigs: AutoCohortConfig[] = [
    // Weekly cohorts by signup week
    {
      name: 'Week 1 - All Users',
      definition: {
        signupDate: {
          gte: getWeekStartDate(-1),
          lt: getWeekStartDate(0),
        },
      },
    },
    {
      name: 'Week 2 - All Users',
      definition: {
        signupDate: {
          gte: getWeekStartDate(-2),
          lt: getWeekStartDate(-1),
        },
      },
    },
    {
      name: 'Week 3 - All Users',
      definition: {
        signupDate: {
          gte: getWeekStartDate(-3),
          lt: getWeekStartDate(-2),
        },
      },
    },
    {
      name: 'Week 4 - All Users',
      definition: {
        signupDate: {
          gte: getWeekStartDate(-4),
          lt: getWeekStartDate(-3),
        },
      },
    },
    // Premium users by week
    {
      name: 'Week 1 - Premium Users',
      definition: {
        signupDate: {
          gte: getWeekStartDate(-1),
          lt: getWeekStartDate(0),
        },
        planType: 'premium',
        hasSubscription: true,
      },
      planType: 'premium',
    },
    // Referral users
    {
      name: 'Week 1 - Referral Users',
      definition: {
        signupDate: {
          gte: getWeekStartDate(-1),
          lt: getWeekStartDate(0),
        },
        signupSource: 'referral',
      },
      signupSource: 'referral',
    },
    // Mobile users
    {
      name: 'Week 1 - Mobile Users',
      definition: {
        signupDate: {
          gte: getWeekStartDate(-1),
          lt: getWeekStartDate(0),
        },
        platform: 'mobile',
      },
      platform: 'mobile',
    },
  ];

  for (const config of cohortConfigs) {
    try {
      const userIds = await findUsersMatchingCriteria(config.definition);

      if (userIds.length === 0) {
        console.log(`Skipping cohort "${config.name}" - no users found`);
        continue;
      }

      // Check if cohort already exists
      const existing = await prisma.userCohort.findUnique({
        where: { name: config.name },
      });

      if (existing) {
        // Update existing cohort
        await prisma.userCohort.update({
          where: { id: existing.id },
          data: {
            definition: config.definition,
            userIds,
            platform: config.platform,
            country: config.country,
            planType: config.planType,
            signupSource: config.signupSource,
            autoGenerated: true,
          },
        });
        console.log(`Updated cohort "${config.name}" with ${userIds.length} users`);
      } else {
        // Create new cohort
        await prisma.userCohort.create({
          data: {
            name: config.name,
            definition: config.definition,
            userIds,
            platform: config.platform,
            country: config.country,
            planType: config.planType,
            signupSource: config.signupSource,
            autoGenerated: true,
          },
        });
        console.log(`Created cohort "${config.name}" with ${userIds.length} users`);
      }
    } catch (error) {
      console.error(`Error generating cohort "${config.name}":`, error);
    }
  }

  console.log('Automatic cohort generation completed');
}

/**
 * Get week start date (Monday)
 */
function getWeekStartDate(weeksAgo: number): string {
  const date = new Date();
  date.setDate(date.getDate() - (weeksAgo * 7));
  
  // Get Monday of that week
  const day = date.getDay();
  const diff = date.getDate() - day + (day === 0 ? -6 : 1); // Adjust when day is Sunday
  date.setDate(diff);
  date.setHours(0, 0, 0, 0);
  
  return date.toISOString();
}


