/**
 * Cohort Analysis Component
 * Main component for cohort analysis dashboard
 */

import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { RetentionMatrix } from './RetentionMatrix';
import { CohortMetricsCharts } from './CohortMetricsCharts';
import { Plus, RefreshCw } from 'lucide-react';
import { api, apiRequest, getHeaders } from '@/lib/api';
import { useToast } from '@/hooks/use-toast';
import { Skeleton } from '@/components/ui/skeleton';

interface Cohort {
  id: string;
  name: string;
  userCount: number;
  metricsCount: number;
  platform?: string;
  country?: string;
  planType?: string;
  signupSource?: string;
  autoGenerated?: boolean;
  createdAt: string;
}

interface CohortData {
  id: string;
  name: string;
  userIds: string[];
  retentionByWeek: number[];
  metrics: {
    week: number;
    activeUsers: number;
    newUsers: number;
    churnedUsers: number;
    avgWatchTime: number;
    avgRevenue: number;
    retention: number;
  }[];
}

export function CohortAnalysis() {
  const { toast } = useToast();
  const [cohorts, setCohorts] = useState<Cohort[]>([]);
  const [selectedCohortId, setSelectedCohortId] = useState<string>('');
  const [cohortData, setCohortData] = useState<CohortData | null>(null);
  const [loading, setLoading] = useState(true);
  const [_loadingData, setLoadingData] = useState(false);
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [newCohortName, setNewCohortName] = useState('');
  const [creating, setCreating] = useState(false);

  // Filters state for cohort filtering
  const [filters] = useState<{
    platform?: string;
    country?: string;
    planType?: string;
    signupSource?: string;
    region?: string;
  }>({});

  useEffect(() => {
    loadCohorts();
  }, []);

  useEffect(() => {
    if (selectedCohortId) {
      loadCohortData(selectedCohortId);
    }
  }, [selectedCohortId]);

  const loadCohorts = async () => {
    try {
      // Build query params for filtering
      const params = new URLSearchParams();
      if (filters.platform) params.append('platform', filters.platform);
      if (filters.country) params.append('country', filters.country);
      if (filters.planType) params.append('planType', filters.planType);
      if (filters.signupSource) params.append('signupSource', filters.signupSource);
      if (filters.region) params.append('region', filters.region);

      const url = `/api/cohorts${params.toString() ? `?${params.toString()}` : ''}`;
      const response = await apiRequest<Cohort[]>(url, {
        method: 'GET',
        headers: getHeaders(),
      });

      if (response.success && response.data) {
        setCohorts(response.data);
        if (response.data.length > 0 && !selectedCohortId) {
          setSelectedCohortId(response.data[0].id);
        }
      }
    } catch (error: any) {
      console.error('Failed to load cohorts:', error);
      toast({
        title: 'Error',
        description: 'Failed to load cohorts',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  const loadCohortData = async (cohortId: string) => {
    setLoadingData(true);
    try {
      const response = await api.cohorts.getById<CohortData>(cohortId);
      if (response.success && response.data) {
        setCohortData(response.data);
      }
    } catch (error: any) {
      console.error('Failed to load cohort data:', error);
      toast({
        title: 'Error',
        description: 'Failed to load cohort data',
        variant: 'destructive',
      });
    } finally {
      setLoadingData(false);
    }
  };

  const handleGenerateCohorts = async () => {
    try {
      const response = await api.cohorts.generate();
      if (response.success) {
        toast({
          title: 'Success',
          description: 'Cohorts generated successfully',
        });
        loadCohorts();
      }
    } catch (error: any) {
      toast({
        title: 'Error',
        description: error.message || 'Failed to generate cohorts',
        variant: 'destructive',
      });
    }
  };

  const handleCreateCohort = async () => {
    if (!newCohortName.trim()) {
      toast({
        title: 'Error',
        description: 'Please enter a cohort name',
        variant: 'destructive',
      });
      return;
    }

    setCreating(true);
    try {
      // Simple definition - can be expanded
      const definition = {
        signupDate: {
          gte: new Date().toISOString().split('T')[0],
        },
      };

      const response = await api.cohorts.create({
        name: newCohortName,
        definition,
      });

      if (response.success) {
        toast({
          title: 'Success',
          description: 'Cohort created successfully',
        });
        setShowCreateDialog(false);
        setNewCohortName('');
        loadCohorts();
      }
    } catch (error: any) {
      toast({
        title: 'Error',
        description: error.message || 'Failed to create cohort',
        variant: 'destructive',
      });
    } finally {
      setCreating(false);
    }
  };

  const handleCalculateMetrics = async () => {
    if (!selectedCohortId) return;

    try {
      const response = await api.cohorts.calculateMetrics(selectedCohortId);
      if (response.success) {
        toast({
          title: 'Success',
          description: 'Metrics calculated successfully',
        });
        loadCohortData(selectedCohortId);
      }
    } catch (error: any) {
      toast({
        title: 'Error',
        description: error.message || 'Failed to calculate metrics',
        variant: 'destructive',
      });
    }
  };

  if (loading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-32" />
        <Skeleton className="h-64" />
      </div>
    );
  }

  // Prepare data for charts
  const revenueData = cohortData?.metrics.map(m => ({
    week: m.week,
    revenue: m.avgRevenue,
  })) || [];

  const engagementData = cohortData?.metrics.map(m => ({
    week: m.week,
    avgWatchTime: Math.round((m.avgWatchTime || 0) / 60), // Convert seconds to minutes
  })) || [];

  return (
    <div className="space-y-6">
      {/* Cohort Selector */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Cohort Analysis</CardTitle>
              <CardDescription>Analyze user behavior by cohort</CardDescription>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" onClick={handleGenerateCohorts}>
                <RefreshCw className="h-4 w-4 mr-2" />
                Generate Cohorts
              </Button>
              <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
                <DialogTrigger asChild>
                  <Button>
                    <Plus className="h-4 w-4 mr-2" />
                    Create Cohort
                  </Button>
                </DialogTrigger>
                <DialogContent>
                  <DialogHeader>
                    <DialogTitle>Create New Cohort</DialogTitle>
                    <DialogDescription>
                      Create a new user cohort for analysis
                    </DialogDescription>
                  </DialogHeader>
                  <div className="space-y-4">
                    <div>
                      <Label htmlFor="cohort-name">Cohort Name</Label>
                      <Input
                        id="cohort-name"
                        value={newCohortName}
                        onChange={(e) => setNewCohortName(e.target.value)}
                        placeholder="e.g., January 2025 Signups"
                      />
                    </div>
                    <Button onClick={handleCreateCohort} disabled={creating} className="w-full">
                      {creating ? 'Creating...' : 'Create Cohort'}
                    </Button>
                  </div>
                </DialogContent>
              </Dialog>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="flex items-center gap-4">
            <div className="flex-1">
              <Label>Select Cohort</Label>
              <Select value={selectedCohortId} onValueChange={setSelectedCohortId}>
                <SelectTrigger>
                  <SelectValue placeholder="Select a cohort" />
                </SelectTrigger>
                <SelectContent>
                  {cohorts.map((cohort) => (
                    <SelectItem key={cohort.id} value={cohort.id}>
                      {cohort.name} ({cohort.userCount} users)
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            {selectedCohortId && (
              <Button variant="outline" onClick={handleCalculateMetrics}>
                Calculate Metrics
              </Button>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Retention Matrix */}
      {cohortData && (
        <RetentionMatrix
          cohorts={[
            {
              id: cohortData.id,
              name: cohortData.name,
              retentionByWeek: cohortData.retentionByWeek,
            },
          ]}
        />
      )}

      {/* Metrics Charts */}
      {cohortData && (
        <CohortMetricsCharts
          revenueData={revenueData}
          engagementData={engagementData}
        />
      )}

      {!selectedCohortId && (
        <Card>
          <CardContent className="py-12 text-center text-muted-foreground">
            Select a cohort to view analysis
          </CardContent>
        </Card>
      )}
    </div>
  );
}

